jobs:
- name: package
  plan:
  - get: source-code
    trigger: true
  - task: package
    privileged: true
    file: source-code/ci/tasks/package.yml
  - put: resource-deploy-web-app
    params:
      manifest: source-code/manifest.yml
      path: target/concourse-spring-boot-maven-0.0.1-SNAPSHOT.jar
